export const organisations = ['Woodcraft Folk',
 'OGCEYOD – Organisation for Gender',
 'Civic Engagement and Youth Development - Cameroon',
 'ASYOUSED – Assembly of Youths for a Sustainable Environment andDevelopment - Cameroon',
 'YAG - Youth Advocates Ghana Ghana',
 'YOBEC – Youth for Behaviour Change - Liberia',
 'Pioneers of Mali -  Mali',
 'Action Enfance -  Senegal',
 'Pioneers of Senegal - Senegal',
 'USARJO – Union de la Juventud de Saguia el Hamra y Rio de Oro - Western Sahara',
 'KKSP Foundation - Indonesia',
 'Antar Bharati -  India',
 'Ram Manohar Lohia International Trust - India',
 'Armenian Youth Federation -  Armenia',
 'Kinderfreunde - Rote Falken  - Austria',
 'The Falcons Belarus - Belarus',
 'Faucons Rouges - Belgium',
 'Rode Valken - Belgium',
 'Pionýr - Czech Republic',
 'DUI - LEG OG VIRKE - Denmark',
 'Nuorten Kotkien Keskuslitto - Finland',
 'Georgian Falcons - Georgia',
 'Sozialistische Jugend Deutschlands – Die Falken - Germany',
 'Hungarian Childfriends - Hungary',
 'Arciragazzi - Italy',
 'Liepajas Jaunie Vanagi - Latvia',
 'Lithuanian Young Falcon Union - Lithuania',
 'Framfylkingen - Norway',
 'Fénix - Slovakia',
 'Esplac - Catalunya',
 'Unga Örnar - Sweden',
 'Rote Falken Schweiz - Switzerland',
 'Instituto Moises Lebensohn -  Argentina',
 'Nueva Generación - Bolivia',
 'MIRIM Brasil Brazil -  Amizade',
 'Agrupación Integridad Absoluta - Chile',
 'Manque Chile - Chile',
 'Fundación Acacia - Colombia',
 'Falcons of Ecuador Equador Mentes en Accion - Honduras',
 'MILAVF – Movimiento Infantil Luis',
 'Alfonso Velasquez Flores - Nicaragua',
 'Club Infantil “23 de Mayo” CHAP - Peru',
 'Los Cachorros - Peru',
 'Mundo Nuevo - Peru',
 'ADICR – Association for the Rights of Iranian Children - Iran',
 'Hashomer Hatzair - Israel',
 'Noar Oved Vehalomed - Israel',
 'Independence Youth Union - Palestine',
 'Independent Youth Forum - Palestine',
 'Palestinian Red Crescent Society -  Palestine']