export const organisations = [["Woodcraft Folk","Western and Northern Europe and North America"],
["OGCEYOD – Organisation for Gender", "Middle East, Latin America, Asia, and Africa"],
["Civic Engagement and Youth Development - Cameroon", "Middle East, Latin America, Asia, and Africa"],
["ASYOUSED – Assembly of Youths for a Sustainable Environment and Development - Cameroon", "Middle East, Latin America, Asia, and Africa"],
["YAG - Youth Advocates Ghana Ghana", "Middle East, Latin America, Asia, and Africa"],
["YOBEC – Youth for Behaviour Change - Liberia", "Middle East, Latin America, Asia, and Africa"],
["Pioneers of Mali - Mali", "Middle East, Latin America, Asia, and Africa"],
["Action Enfance - Senegal", "Middle East, Latin America, Asia, and Africa"],
["Pioneers of Senegal - Senegal", "Middle East, Latin America, Asia, and Africa"],
["USARJO – Union de la Juventud de Saguia el Hamra y Rio de Oro - Western Sahara", "Middle East, Latin America, Asia, and Africa"],
["KKSP Foundation - Indonesia", "Middle East, Latin America, Asia, and Africa"],
["Antar Bharati - India", "Middle East, Latin America, Asia, and Africa"],
["Ram Manohar Lohia International Trust - India", "Middle East, Latin America, Asia, and Africa"],
["Armenian Youth Federation - Armenia", "Middle East, Latin America, Asia, and Africa"],
["Kinderfreunde - Rote Falken - Austria", "Western and Northern Europe and North America"],
["The Falcons Belarus - Belarus", "Eastern Europe"],
["Faucons Rouges - Belgium", "Western and Northern Europe and North America"],
["Rode Valken - Belgium", "Western and Northern Europe and North America"],
["Pionýr - Czech Republic", "Eastern Europe"],
["DUI - LEG OG VIRKE - Denmark", "Western and Northern Europe and North America"],
["Nuorten Kotkien Keskuslitto - Finland", "Western and Northern Europe and North America"],
["Georgian Falcons - Georgia", "Eastern Europe"],
["Sozialistische Jugend Deutschlands – Die Falken - Germany", "Western and Northern Europe and North America"],
["Hungarian Childfriends - Hungary", "Eastern Europe"],
["Arciragazzi - Italy", "Western and Northern Europe and North America"],
["Liepajas Jaunie Vanagi - Latvia", "Eastern Europe"],
["Lithuanian Young Falcon Union - Lithuania", "Eastern Europe"],
["Framfylkingen - Norway", "Western and Northern Europe and North America"],
["Fénix - Slovakia", "Eastern Europe"],
["Esplac - Catalunya", "Western and Northern Europe and North America"],
["Unga Örnar - Sweden", "Western and Northern Europe and North America"],
["Rote Falken Schweiz - Switzerland", "Western and Northern Europe and North America"],
["Instituto Moises Lebensohn - Argentina", "Middle East, Latin America, Asia, and Africa"],
["Nueva Generación - Bolivia", "Middle East, Latin America, Asia, and Africa"],
["MIRIM Brasil Brazil - Amizade", "Middle East, Latin America, Asia, and Africa"],
["Agrupación Integridad Absoluta - Chile", "Middle East, Latin America, Asia, and Africa"],
["Manque Chile - Chile", "Middle East, Latin America, Asia, and Africa"],
["Fundación Acacia - Colombia", "Middle East, Latin America, Asia, and Africa"],
["Falcons of Ecuador Equador Mentes en Accion - Honduras", "Middle East, Latin America, Asia, and Africa"],
["MILAVF – Movimiento Infantil Luis", "Middle East, Latin America, Asia, and Africa"],
["Alfonso Velasquez Flores - Nicaragua", "Middle East, Latin America, Asia, and Africa"],
["Club Infantil “23 de Mayo” CHAP - Peru", "Middle East, Latin America, Asia, and Africa"],
["Los Cachorros - Peru", "Middle East, Latin America, Asia, and Africa"],
["Mundo Nuevo - Peru", "Middle East, Latin America, Asia, and Africa"],
["ADICR – Association for the Rights of Iranian Children - Iran", "Middle East, Latin America, Asia, and Africa"],
["Hashomer Hatzair - Israel", "Middle East, Latin America, Asia, and Africa"],
["Noar Oved Vehalomed - Israel", "Middle East, Latin America, Asia, and Africa"],
["Independence Youth Union - Palestine", "Middle East, Latin America, Asia, and Africa"],
["Independent Youth Forum - Palestine", "Middle East, Latin America, Asia, and Africa"],
["Palestinian Red Crescent Society - Palestine	MIDDLE	Middle East, Latin America, Asia, and Africa"]]