name: Build and Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment to deploy to'

permissions:
  id-token: write
  contents: read

concurrency: 
  group: ${ {inputs.environment }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      NODE_ENV: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role
          role-session-name: terraform-session
          aws-region: eu-west-2

      - name: install base
        run: |
          npm ci --include=dev --legacy-peer-deps

      - name: install layer
        working-directory: common-layer/nodejs
        run: |
          npm ci --include=dev --legacy-peer-deps

      - name: build lambdas
        run: |
          node esbuild-lambda.cjs 

      - name: build front
        run: |
          node esbuild-front.mjs 

      - name: terraform init
        working-directory: terraform
        run: |
          terraform init -backend-config "bucket=bookings-nosql-terraform-state-${{ github.ref_name }}"

      - name: terraform apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve