name: Build Main

on:
  push:
    branches:
      - camp100
      
  workflow_dispatch:    

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Deploy
    uses: ./.github/workflows/build-reusable.yaml
    secrets: inherit
    with:
      environment: camp100
