name: Build Main

on:
  push:
    branches:
      - main
      
  workflow_dispatch:    

jobs:
  build:
    name: Build and Deploy
    uses: .github/workflows/build-reusable.yaml@main
    with:
      environment: nosql