name: Build Main

on:
  push:
    branches:
      - main
      
  workflow_dispatch:    

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Deploy
    environment: nosql
    secrets: inherit
    uses: ./.github/workflows/build-reusable.yaml